image:
  - Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:/Python36-x64"
    - PYTHON: "C:/Python37-x64"
    - PYTHON: "C:/Python38-x64"
  MINGW_DIR: C:/msys64/mingw64/bin

clone_depth: 5

init:
  - cmd: set PATH=%MINGW_DIR%;%PATH%

build: off

after_test:
  - "%PYTHON%\\python.exe setup.py prepare"
  - "%PYTHON%\\python.exe build_ext --inplace --compiler=mingw32 --fcompiler=gnu95 -f"
  - "%PYTHON%\\python.exe bdist_wheel"
 
artifacts:
  - path: dist\*