image: python:3.7

stages:
#  - test
  - build
#  - publish

#test:
#  stage: test
#  script:
#    - echo "Testing"
#    - apt-get update
#    - apt-get install -y gfortran
#    - pip3 install -e .
#    - pip3 install nose2
#    - nose2 -v

dist:
  image: quay.io/pypa/manylinux2010_x86_64
  stage: build
  script:
    - CI/build-wheel-manylinux.sh
#    - echo "Building distribution"
#    - apt-get update
#    - apt-get install -y gfortran
#    - python3 setup.py sdist
#    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
#  only:
#    - tags

#testpypi:
#  stage: publish
#  variables:
#    TWINE_USERNAME: $TESTPYPI_USERNAME
#    TWINE_PASSWORD: $TESTPYPI_PASSWORD
#  script:
#    - pip install twine
#    - echo "Upload to testpypi"
#    - twine upload --repository testpypi dist/*
#  only:
#    - tags



